#:import os os


<CardCall>
    orientation: "vertical"

    MDBoxLayout:
        orientation: "vertical"
        adaptive_height: True

        MDLabel:
            shorten: True
            shorten_from: "right"
            color: 1, 1, 1, 1
            markup: True
            adaptive_height: True
            pos_hint: {"center_y": .1}


        MDBoxLayout:
            adaptive_height: True


